baseURL = "https://www.janmazza.com"
languageCode = "en-us"
theme = "adritian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Research"
  URL = "/research"
  weight = 2

  [[menu.header]]
  name = "Teaching"
  URL = "/teaching"
  weight = 3

  [[menu.header]]
  name = "CV"
  URL = "/resume.pdf"
  weight = 4

  [[menu.header]]
  name = "Media"
  URL = "/media"
  weight = 5

  


  [[menu.footer]]
  name = "Research"
  URL = "/research"
  weight = 2

  [[menu.footer]]
  name = "Teaching"
  URL = "/teaching"
  weight = 3

  [[menu.footer]]
  name = "CV"
  URL = "/resume.pdf"
  weight = 4

  [[menu.footer]]
  name = "Media"
  URL = "/media"
  weight = 5



[params]

  sections = ["showcase"]

  googleTagManagerID = "G-ZV7NMN1EJS" # Google Analytics works with Google Tag Manager
  homepageExperienceCount = 6
  
  [params.logo]
    text1 = "Jan Mazza"
    text2 = ""

  [params.footer]
      copyright = "© Adritian. Free Hugo theme by Adrián Moreno Peña."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"

